### PR TITLE
Update Velero to 1.1.0 and operator-sdk to 0.12.0

### PR DESCRIPTION
**Pull request by cblecker**
This change updates Velero to v1.1.0, and the operator-sdk to 0.12.0

### CODE REVIEW

**Comment by cblecker** [comment]
/hold
To pause retesting

**Comment by wanghaoran1988** [comment]
Do we already have a grement to use operator-sdk 0.12.0?

**Comment by cblecker** [comment]
/hold cancel
@wanghaoran1988 There is nothing in our team norms that currently limits or specifies the operator-sdk version we should use.

**Pull request merged**
