### PR TITLE
remove achvatal from owners

### PR DESCRIPTION
**Pull request by yithian**
:saluting_face:

### CODE REVIEW

**Comment by cblecker** [comment]
@yithian I think you need to remove that line via boilerplate. But if you're trying to stop reviews from coming in for you, the line you want to remove is https://github.com/openshift/managed-velero-operator/blob/af26054914576382dc1782b1523052a17090ed74/OWNERS#L4

**Comment by yithian** [comment]
> @yithian I think you need to remove that line via boilerplate. But if you're trying to stop reviews from coming in for you, the line you want to remove is
> 
> https://github.com/openshift/managed-velero-operator/blob/af26054914576382dc1782b1523052a17090ed74/OWNERS#L4

boilerplate has already been updated https://github.com/openshift/boilerplate/commit/b987b220a2248d105af7e0385ee9ccf4537c2524

**Comment by cblecker** [comment]
@yithian Then yes, you'll want to remove the line I mentioned as opposed to touching OWNERS_ALIASES at all

**Pull request closed without merging**
