### PR TITLE
Remove Platform status workaround for 4.1.z

### PR DESCRIPTION
**Pull request by dak1n1**
Since all OSD clusters have been upgraded, we can remove
legacy code that used to look through the configmap to get
platform status information. (OSD 4.2+ stores this information
in the infrastructure CR instead).

https://issues.redhat.com/browse/OSD-2646

### CODE REVIEW

**Comment by dak1n1** [comment]
Tested in stage `quay.io/sedgar/managed-velero-operator:v0.1.73-feb78f3`.

**Comment by c-e-brumm** [comment]
Curious why a role and role binding is being delete here. Seems unrelated.

**Comment by dak1n1** [comment]
The role and rolebinding exist to grant permission to read the `cluster-config-v1` configmap from the kube-system namespace. That's the legacy location for the Platform Status information. This commit removes all references to the legacy Platform Status, including the related RBAC roles.

**Pull request merged**
