### PR TITLE
Add function to get AWS platform and region

### PR DESCRIPTION
**Pull request by cblecker**

### CODE REVIEW

**Comment by c-e-brumm** [comment]
With "kube-system" "cluster-config-v1" and "install-config" all as  hardcoded strings is there a future where this pkg grows and we benefit from moving those to constants? If not that's fine.

**Comment by cblecker** [comment]
@c-e-brumm Good question! The cluster-config-v1 configmap is actually being deprecated and is removed completely in 4.2 (that's the reason for this PR). This allows the code to work under both a 4.1 and 4.2 scenario. As those hard coded strings all relate to 4.1 world, I don't think they would benefit from moving to constants.

**Comment by c-e-brumm** [comment]
lgtm

**Pull request merged**
