### PR TITLE
Move velero/v1alpha1 to veleroinstall/v1alpha2

### PR DESCRIPTION
**Pull request by cblecker**

### CODE REVIEW

**Comment by mbarnes** [comment]
/lgtm

Pretty straight-forward.
Take this as a one-of-two approval, so @luis-falcon still has a chance to see it.

**Comment by cblecker** [comment]
@mbarnes @luis-falcon I've rebased this on top of your changes. Please review this again on Monday. Thanks!

**Comment by cblecker** [comment]
/hold
for review

**Pull request merged**
