### PR TITLE
add resource requests/limits per OSD-2109

### PR DESCRIPTION
**Pull request by bmeng**
current resource usage for the operator:
managed-velero-operator-788b79c77d-j2fjj   1m           20Mi

### CODE REVIEW

**Comment by bmeng** [comment]
@cblecker could you help take a look on this?

**Comment by cblecker** [comment]
@bmeng How were these resource requests/limits determined?

**Comment by bmeng** [comment]
> @bmeng How were these resource requests/limits determined?

Set the resource requests based on the current usage and set the limits with 2x of the usage.
If there are more reasonable values we can change them.

**Comment by cblecker** [comment]
this operator (like many, will use very little resources while it's watching resources after its initial setup, but will use more during startup.

**Comment by bmeng** [comment]
Tested on stage env, with the resource limits/requests setting on the operator, it can be created and running successfully. Do you think it is safe to set the values?

```
Containers:
  managed-velero-operator:
...
    State:          Running
      Started:      Tue, 12 May 2020 13:13:31 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     20m
      memory:  100Mi
    Requests:
      cpu:     10m
      memory:  50Mi
...
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
...
Events:
  Type    Reason     Age        From                                  Message
  ----    ------     ----       ----                                  -------
  Normal  Scheduled  <unknown>  default-scheduler                     Successfully assigned openshift-velero/managed-velero-operator-5855bf648-8g52t to ip-10-0-128-72.ec2.internal
  Normal  Pulled     7m7s       kubelet, ip-10-0-128-72.ec2.internal  Container image "quay.io/openshift-sre/managed-velero-operator:v0.2.150-3829d1b" already present on machine
  Normal  Created    7m4s       kubelet, ip-10-0-128-72.ec2.internal  Created container managed-velero-operator
  Normal  Started    7m4s       kubelet, ip-10-0-128-72.ec2.internal  Started container managed-velero-operator

```

**Comment by bmeng** [comment]
@cblecker should we review this due to the recent velero memory leak problem?

I have just adjusted the value for both request and limit.

**Pull request closed without merging**
