### PR TITLE
OSD 7598 - boilerplate update + transitioning to crd v1

### PR DESCRIPTION
**Pull request by bng0y**

### CODE REVIEW

**Comment by 2uasimojo** [comment]
Need to hold these PRs pending boilerplate updates to handle CRD v1 in the appsre pipeline script for bundle generation.

**Comment by 2uasimojo** [comment]
bp commit level is good (includes crd v1 + fix)

New CRD installs cleanly, and `oc explain` works.

/lgtm

**Review by fahlmant — APPROVED** [review]
/hold cancel
/lgtm

**Pull request merged**
